apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: medi-aide
  namespace: argocd
spec:
  description: Medi-Aide applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true

