apiVersion: v1
kind: Secret
metadata:
  name: notification-service-db
  namespace: medi-aide
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: stage3
type: Opaque
stringData:
  host: "stage3-postgres.medi-aide.svc.cluster.local"
  port: "5432"
  user: "postgres"
  password: "postgres" # Replace with actual password in production
  name: "notification_db"
