apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: medi-aide
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: stage3
type: Opaque
stringData:
  url: "amqp://guest:guest@rabbitmq.medi-aide.svc.cluster.local:5672" # Replace with actual credentials in production
