{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nest-service.fullname" . }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nest-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - path: {{ .Values.serviceMonitor.path }}
      port: http
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}


