{{- range $serviceName, $serviceConfig := .Values.services }}
{{- if $serviceConfig.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-service
  labels:
    {{- include "medi-aide.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $serviceConfig.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "medi-aide.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
{{- end }}
{{- end }}

